{% set version = "0.4.0" %}
{% set sha256 = "6b69e8d478a09e503c67f7235c77bef3c0ed3481dadb7dda0ad24c33599a5f1a" %}

package:
  name: xpdsim
  version: {{ version }}

source:
  url: https://github.com/xpdAcq/xpdSim/releases/download/{{ version }}/xpdSim-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ophyd=1.3.3
    - pyfai
    - databroker=0.13.0
    - bluesky

test:
  imports:
    - xpdsim

about:
  home: http://xpdacq.github.io/xpdSim/
  license_file: LICENSE
  summary: Simulator objects for bluesky and ophyd
