{% set version = "0.4.0" %}

package:
  name: xpdsim
  version: {{ version }}

source:
  git_url: https://github.com/xpdAcq/xpdSim.git
  git_rev: {{ version }}
  git_depth: -1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ophyd=1.3.3
    - pyfai
    - databroker=0.13.0
    - bluesky

test:
  imports:
    - xpdsim

about:
  home: http://xpdacq.github.io/xpdSim/
  license_file: LICENSE
